GET http://localhost:3000/ttech HTTP/1.1

###

GET http://localhost:3000/ HTTP/1.1

###

GET http://localhost:3000/students HTTP/1.1
###

DELETE http://localhost:3000/students/6660cf26b2d884aa33bed001 HTTP/1.1

###

GET http://localhost:3000/students/6660bba4987b5c288bb3f924 HTTP/1.1

###
POST http://localhost:3000/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Phil",
    "lastName": "Reeves",
    "email": "bowser@killer.com",
    "age": 34,
    "currentCollege": "Assassin's Academy"
}
###
PUT http://localhost:3000/students/6660ccaf2beabff4a99f1e19 HTTP/1.1
Content-Type: application/json

{
    "firstName": "john",
    "lastName": "Reeves",
    "email": "bowser@killer.com",
    "age": 34,
    "currentCollege": "Assassin's Academy"
}